/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package com.eomcs.pms;

import java.io.IOException;
import java.io.InputStreamReader;
import java.io.PrintStream;
import java.net.Socket;
import java.net.UnknownHostException;
import java.util.Scanner;

// Stateful 통신 
// => 서버와 연결하여 간단한 메시지 주고 받기
//
public class ClientApp {
  public static void main(String[] args) throws UnknownHostException, IOException {
    // 서버 주소: localhost
    // 서버 포트: 8888
    //
    // 1. 서버와 연결된 소켓을 생성한다.
    // 2. 소켓을 통해 문자열을 입출력할 수 있도록 스트림 객체를 준비한다.
    // 먼저 서버에 간단한 인삿말을 보낸다.
    // 서버가 응답한 메시지를 출력한다.
    try (Socket socket = new Socket("localhost", 8888);
        Scanner in = new Scanner(new InputStreamReader(socket.getInputStream()));
        PrintStream out = new PrintStream(socket.getOutputStream())) {
      out.println("안녕하세요!");
      System.out.println(in.nextLine());
    }
  }
}
